### ISSUE TITLE
Segmentation fault when more than 16 data structures

### ISSUE THREAD

**Issue by jordan-wright** [apiaryio/protagonist#116]
This is referenced in https://github.com/danielgtaylor/aglio/issues/213.

Specifically, using the test file in the gist from that issue and the following script:

```
fs = require("fs")
prot = require('protagonist');
fs.readFile("test.apib", "utf8", function(err, data){
        if (err) {
                return console.log(err)
        }
        prot.parse(data, function(error, result){
                if (error) {
                        return console.log(error)
                }
                console.log(result)
        })
})
```

We get a segmentation fault. Here is the segmentation fault I received on my instance:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7785418 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7785418 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff689b0ca in drafter::InheritanceComparator::operator()(snowcrash::DataStructure const*, snowcrash::DataStructure const*) ()
   from /root/docs/node_modules/protagonist/build/Release/protagonist.node
#2  0x00007ffff689c7aa in void std::__introsort_loop<__gnu_cxx::__normal_iterator<snowcrash::DataStructure const**, std::vector<snowcrash::DataStructure const*, std::allocator<snowcrash::DataStructure const*> > >, long, drafter::InheritanceComparator>(__gnu_cxx::__normal_iterator<snowcrash::DataStructure const**, std::vector<snowcrash::DataStructure const*, std::allocator<snowcrash::DataStructure const*> > >, __gnu_cxx::__normal_iterator<snowcrash::DataStructure const**, std::vector<snowcrash::DataStructure const*, std::allocator<snowcrash::DataStructure const*> > >, long, drafter::InheritanceComparator) ()
   from /root/docs/node_modules/protagonist/build/Release/protagonist.node
#3  0x00007ffff689ce17 in drafter::RegisterNamedTypes(std::vector<snowcrash::Element, std::allocator<snowcrash::Element> > const&) ()
   from /root/docs/node_modules/protagonist/build/Release/protagonist.node
#4  0x00007ffff688cd77 in WrapParseResultRefract(snowcrash::ParseResult<snowcrash::Blueprint> const&, drafter::WrapperOptions const&) ()
   from /root/docs/node_modules/protagonist/build/Release/protagonist.node
#5  0x00007ffff6892fb9 in drafter::WrapResult(snowcrash::ParseResult<snowcrash::Blueprint> const&, drafter::WrapperOptions const&) ()
   from /root/docs/node_modules/protagonist/build/Release/protagonist.node
#6  0x00007ffff688abab in protagonist::Result::WrapResult(snowcrash::ParseResult<snowcrash::Blueprint>&, unsigned int const&, drafter::ASTType const&) ()
   from /root/docs/node_modules/protagonist/build/Release/protagonist.node
#7  0x00007ffff688730f in AsyncParseAfter(uv_work_s*) () from /root/docs/node_modules/protagonist/build/Release/protagonist.node
#8  0x0000000000dd71dd in uv.work_done ()
#9  0x0000000000dd90e6 in ?? ()
#10 0x0000000000dd91c3 in ?? ()
#11 0x0000000000de898d in uv.io_poll ()
#12 0x0000000000dd9d16 in uv_run ()
#13 0x0000000000c3a911 in node::Start(int, char**) ()
#14 0x00007ffff6becec5 in __libc_start_main (main=0x69c500 <main>, argc=2, argv=0x7fffffffe6b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffe6a8) at libc-start.c:287
#15 0x000000000069c6ef in _start ()
```

Settings:

```
root@api-docs:~/docs# nodejs -v
v0.12.9
root@api-docs:~/docs# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
```

**Comment by jordan-wright** [comment]
Closing, as this appears to be an issue with drafter, not protagonist:

https://github.com/apiaryio/drafter/issues/207

**Comment by wadey** [comment]
@jordan-wright The submodule in this repo for drafter still needs to be updated to the fixed version.

**Comment by jordan-wright** [comment]
Good point. I'll go ahead and re-open until the submodule is updated.

**Comment by jordan-wright** [comment]
Does anyone know when this will get updated? Are we waiting on drafter to release an updated version?

**Comment by w-vi** [comment]
@jordan-wright: Tommorrow, on Monday before lunch GMT

**Comment by kylef** [comment]
Protagonist 1.2.4 is now out (https://github.com/apiaryio/protagonist/releases/tag/v1.2.4).

**Comment by jordan-wright** [comment]
Excellent, thanks @kylef and team!
