### ISSUE TITLE
Failed to build protagonist on node.js 5

### ISSUE THREAD

**Issue by peterkomar** [apiaryio/protagonist#131]
```
../drafter/ext/snowcrash/src/MSONSourcemap.h:177: warning: ‘auto_ptr’ is deprecated (declared at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/backward/auto_ptr.h:86)
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/Element.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/VisitorUtils.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/SerializeCompactVisitor.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/SerializeVisitor.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/ComparableVisitor.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/TypeQueryVisitor.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/IsExpandableVisitor.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/ExpandVisitor.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/RenderJSONVisitor.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/PrintVisitor.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/JSONSchemaVisitor.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/refract/Registry.o
  AR(target) Release/obj.target/drafter/drafter.a
  COPY Release/drafter.a
  CXX(target) Release/obj.target/libsos/drafter/ext/sos/src/sos.o
  AR(target) Release/obj.target/drafter/sos.a
  COPY Release/sos.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
In file included from /home/teachers/.node-gyp/5.4.1/include/node/node.h:42,
                 from ../src/protagonist.h:4,
                 from ../src/annotation.cc:1:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:336: error: expected unqualified-id before ‘using’
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:353: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:360: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:364: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:430: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: At global scope:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:469: error: expected unqualified-id before ‘using’
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:794: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:819: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:831: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: At global scope:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:856: error: expected unqualified-id before ‘using’
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:1093: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:1099: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:3204: error: ‘nullptr’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:7154: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:182,
                 from ../src/protagonist.h:6,
                 from ../src/annotation.cc:1:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:65: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:70: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:77: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:84: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:92: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:99: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:109: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:115: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:119: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:126: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:131: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:136: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:140: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:146: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:151: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:157: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:163: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:169: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:175: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:181: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:187: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:195: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:202: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:206: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:210: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:214: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
In file included from ../../nan/nan.h:187,
                 from ../src/protagonist.h:6,
                 from ../src/annotation.cc:1:
../../nan/nan_converters.h:14: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../../nan/nan_converters.h:14: error: expected ‘;’ before ‘<’ token
../../nan/nan_converters.h:16: error: ISO C++ forbids declaration of ‘Maybe’ with no type
../../nan/nan_converters.h:16: error: expected ‘;’ before ‘<’ token
../../nan/nan_converters.h:26: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:27: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:28: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:29: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:30: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:31: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:32: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:42: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:43: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:44: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:45: error: ‘return_t’ does not name a type
../../nan/nan_converters.h:46: error: ‘return_t’ does not name a type
In file included from ../../nan/nan_converters.h:59,
                 from ../../nan/nan.h:187,
                 from ../src/protagonist.h:6,
                 from ../src/annotation.cc:1:
../../nan/nan_converters_43_inl.h:18: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Boolean>’ does not name a type
../../nan/nan_converters_43_inl.h:19: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Number>’ does not name a type
../../nan/nan_converters_43_inl.h:20: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::String>’ does not name a type
../../nan/nan_converters_43_inl.h:21: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Object>’ does not name a type
../../nan/nan_converters_43_inl.h:22: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Integer>’ does not name a type
../../nan/nan_converters_43_inl.h:23: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Uint32>’ does not name a type
../../nan/nan_converters_43_inl.h:24: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Int32>’ does not name a type
../../nan/nan_converters_43_inl.h:34: error: ‘return_t’ in class ‘Nan::imp::ToFactory<bool>’ does not name a type
../../nan/nan_converters_43_inl.h:35: error: ‘return_t’ in class ‘Nan::imp::ToFactory<double>’ does not name a type
../../nan/nan_converters_43_inl.h:36: error: ‘return_t’ in class ‘Nan::imp::ToFactory<long int>’ does not name a type
../../nan/nan_converters_43_inl.h:37: error: ‘return_t’ in class ‘Nan::imp::ToFactory<unsigned int>’ does not name a type
../../nan/nan_converters_43_inl.h:38: error: ‘return_t’ in class ‘Nan::imp::ToFactory<int>’ does not name a type
In file included from ../../nan/nan.h:188,
                 from ../src/protagonist.h:6,
                 from ../src/annotation.cc:1:
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
../../nan/nan_new.h:21: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Int32]’:
../../nan/nan_new.h:28: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Uint32]’:
../../nan/nan_new.h:35: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../../nan/nan_new.h: At global scope:
../../nan/nan_new.h:43: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../../nan/nan_new.h:43: error: expected ‘;’ before ‘<’ token
../../nan/nan_new.h:75: error: ‘return_t’ does not name a type
../../nan/nan_new.h:141: error: ‘return_t’ does not name a type
../../nan/nan_new.h:147: error: ‘return_t’ does not name a type
../../nan/nan_new.h:148: error: ‘return_t’ does not name a type
../../nan/nan_new.h:160: error: ‘return_t’ does not name a type
../../nan/nan_new.h:161: error: ‘return_t’ does not name a type
../../nan/nan_new.h:162: error: ‘return_t’ does not name a type
../../nan/nan_new.h:163: error: ‘return_t’ does not name a type
../../nan/nan_new.h:165: error: ‘return_t’ does not name a type
../../nan/nan_new.h:166: error: ‘return_t’ does not name a type
../../nan/nan_new.h:182: error: ‘return_t’ does not name a type
../../nan/nan_new.h:183: error: ‘return_t’ does not name a type
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:188,
                 from ../src/protagonist.h:6,
                 from ../src/annotation.cc:1:
../../nan/nan_implementation_12_inl.h:56: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Date>’ does not name a type
../../nan/nan_implementation_12_inl.h: In static member function ‘static v8::Local<v8::Function> Nan::imp::Factory<v8::Function>::New(void (*)(const Nan::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:90: error: ‘NewInstance’ was not declared in this scope
../../nan/nan_implementation_12_inl.h: In static member function ‘static v8::Local<v8::FunctionTemplate> Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(const Nan::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Value>, v8::Local<v8::Signature>)’:
../../nan/nan_implementation_12_inl.h:118: error: ‘NewInstance’ was not declared in this scope
../../nan/nan_implementation_12_inl.h: At global scope:
../../nan/nan_implementation_12_inl.h:197: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
../../nan/nan_implementation_12_inl.h:216: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../../nan/nan_implementation_12_inl.h:222: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../../nan/nan_implementation_12_inl.h:254: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:262: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:268: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:275: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:281: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:286: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_implementation_12_inl.h:347: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
../../nan/nan_implementation_12_inl.h:354: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
In file included from ../../nan/nan.h:188,
                 from ../src/protagonist.h:6,
                 from ../src/annotation.cc:1:
../../nan/nan_new.h:291: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:297: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:303: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:309: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:315: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:321: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../../nan/nan_new.h:327: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
In file included from ../src/protagonist.h:6,
                 from ../src/annotation.cc:1:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::Error(const char*)’:
../../nan/nan.h:639: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowError(const char*)’:
../../nan/nan.h:639: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::RangeError(const char*)’:
../../nan/nan.h:640: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowRangeError(const char*)’:
../../nan/nan.h:640: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::ReferenceError(const char*)’:
../../nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowReferenceError(const char*)’:
../../nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::SyntaxError(const char*)’:
../../nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowSyntaxError(const char*)’:
../../nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::TypeError(const char*)’:
../../nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::ThrowTypeError(const char*)’:
../../nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: At global scope:
../../nan/nan.h:651: error: expected initializer before ‘<’ token
../../nan/nan.h:673: error: expected initializer before ‘<’ token
../../nan/nan.h:689: error: expected initializer before ‘<’ token
../../nan/nan.h:702: error: expected initializer before ‘<’ token
../../nan/nan.h:719: error: expected initializer before ‘<’ token
../../nan/nan.h:725: error: expected initializer before ‘<’ token
../../nan/nan.h:733: error: expected initializer before ‘<’ token
../../nan/nan.h:740: error: expected initializer before ‘<’ token
../../nan/nan.h:746: error: expected initializer before ‘<’ token
/home/teachers/.node-gyp/5.4.1/include/node/v8.h: In member function ‘void Nan::Callback::SetFunction(const v8::Local<v8::Function>&)’:
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:3019: error: argument dependent lookup finds ‘class v8::Set’
../../nan/nan.h:1366: error:   in call to ‘Set’
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1488: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../../nan/nan.h:1506: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In member function ‘virtual void Nan::AsyncWorker::HandleErrorCallback()’:
../../nan/nan.h:1540: error: no matching function for call to ‘New(const char*)’
../../nan/nan.h: In function ‘void Nan::SetMethod(const T&, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../../nan/nan.h:1829: error: there are no arguments to ‘GetFunction’ that depend on a template parameter, so a declaration of ‘GetFunction’ must be available
../../nan/nan.h:1829: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../../nan/nan.h:1830: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::SetPrototypeMethod(v8::Local<v8::FunctionTemplate>, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../../nan/nan.h:1842: error: ‘GetFunction’ was not declared in this scope
../../nan/nan.h:1843: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<void>&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:
../../nan/nan.h:1868: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<void>&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../../nan/nan.h:1911: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘void Nan::SetNamedPropertyHandler(v8::Local<v8::ObjectTemplate>, void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&), void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Boolean>&), void (*)(const Nan::PropertyCallbackInfo<v8::Array>&), v8::Local<v8::Value>)’:
../../nan/nan.h:1959: error: ‘NewInstance’ was not declared in this scope
../../nan/nan.h: In function ‘void Nan::SetIndexedPropertyHandler(v8::Local<v8::ObjectTemplate>, void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(uint32_t, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Integer>&), void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Boolean>&), void (*)(const Nan::PropertyCallbackInfo<v8::Array>&), v8::Local<v8::Value>)’:
../../nan/nan.h:2029: error: ‘NewInstance’ was not declared in this scope
In file included from ../src/protagonist.h:6,
                 from ../src/annotation.cc:1:
../../nan/nan.h: In function ‘void Nan::Export(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../../nan/nan.h:2090: error: no matching function for call to ‘New(const char*&)’
../../nan/nan.h:2091: error: ‘GetFunction’ was not declared in this scope
/home/teachers/.node-gyp/5.4.1/include/node/v8.h:3019: error: argument dependent lookup finds ‘class v8::Set’
../../nan/nan.h:2091: error:   in call to ‘Set’
../../nan/nan.h: In constructor ‘Nan::Tap::Tap(v8::Local<v8::Value>)’:
../../nan/nan.h:2098: error: no matching function for call to ‘To(v8::Local<v8::Value>&)’
../../nan/nan.h: In member function ‘void Nan::Tap::ok(bool, const char*)’:
../../nan/nan.h:2111: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../../nan/nan.h: In member function ‘void Nan::Tap::pass(const char*)’:
../../nan/nan.h:2117: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17,
                 from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12,
                 from ../drafter/src/Serialize.h:15,
                 from ../src/protagonist.h:7,
                 from ../src/annotation.cc:1:
../drafter/ext/snowcrash/src/MSON.h: At global scope:
../drafter/ext/snowcrash/src/MSON.h:372: warning: ‘auto_ptr’ is deprecated (declared at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/backward/auto_ptr.h:86)
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:13,
                 from ../drafter/src/Serialize.h:15,
                 from ../src/protagonist.h:7,
                 from ../src/annotation.cc:1:
../drafter/ext/snowcrash/src/MSONSourcemap.h:177: warning: ‘auto_ptr’ is deprecated (declared at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/backward/auto_ptr.h:86)
In file included from ../src/annotation.cc:1:
../src/protagonist.h:22: error: ‘Handle’ is not a member of ‘v8’
../src/protagonist.h:22: error: expected primary-expression before ‘>’ token
../src/protagonist.h:22: error: expected primary-expression before ‘)’ token
../src/protagonist.h:29: error: ‘v8::Handle’ has not been declared
../src/protagonist.h:29: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/protagonist.h:47: error: ‘v8::Handle’ has not been declared
../src/protagonist.h:47: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/annotation.cc:18: error: variable or field ‘Init’ declared void
../src/annotation.cc:18: error: ‘Handle’ was not declared in this scope
../src/annotation.cc:18: error: expected primary-expression before ‘>’ token
../src/annotation.cc:18: error: ‘exports’ was not declared in this scope
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/node_modules/protagonist
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
core-util-is@1.0.2 node_modules/dredd/node_modules/gavel/node_modules/is-type/node_modules/core-util-is -> node_modules/core-util-is
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "protagonist"
npm ERR! node v5.4.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! protagonist@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@1.2.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protagonist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/npm-debug.log
You have new mail in /var/spool/mail/teachers

```

**Comment by w-vi** [comment]
@peterkomar Hi ot looks like you are using unsupported version of compiler, Are you on RHEL or CentOS or similar? You need at least gcc 4.8 or clang 3.4, please see the requirements in the [node README](https://github.com/nodejs/node/tree/v5.x#unix--macintosh)

**Comment by kylef** [comment]
According to the error long this compiler used was GCC 4.4.7, so that will need to be updated.

**Comment by peterkomar** [comment]
@w-vi I use CentOS 6.5

**Comment by w-vi** [comment]
@peterkomar please have a look at this issue how to get it working.

**Comment by peterkomar** [comment]
Thanks, update gcc compiler to new helped
