### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by modess** [apiaryio/protagonist#19]
I've tried installing it on OS X 10.9 and also in a Vagrant machine running Ubuntu 12.04, with the same result. I've also tried installing previous versions of protagonist.

```
$ npm install -g protagonist
npm http GET http://registry.npmjs.org/protagonist
npm http 304 http://registry.npmjs.org/protagonist

> protagonist@0.11.0 install /usr/local/lib/node_modules/protagonist
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at errnoException (child_process.js:998:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:34)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/share/npm/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/protagonist
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! protagonist@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protagonist@0.11.0 install script.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/share/npm/bin/npm" "install" "-g" "protagonist"
npm ERR! cwd /Users/niklas
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/niklas/npm-debug.log
npm ERR! not ok code 0
```

Node and npm versions

```
$ node -v
v0.10.28

$ npm -v
1.4.9
```

**Comment by prashannth** [comment]
The node-gyp EACCES can be solved by changing access and sometimes setting node-gyp python version for npm as follows:

`sudo chown -R $USER /usr/local`

&&

 `npm config set python /usr/bin/python2.7` or 2.6

Worked like a charm!
