### ISSUE TITLE
Debian Installation Errors

### ISSUE THREAD

**Issue by cecchi** [apiaryio/protagonist#22]
``` sh
vagrant@forager-dev:/bright/forager/public$ uname -a
Linux forager-dev 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux
```

``` sh
vagrant@forager-dev:/bright/forager/public$ npm install protagonist
npm http GET https://registry.npmjs.org/protagonist
npm http 200 https://registry.npmjs.org/protagonist
npm http GET https://registry.npmjs.org/protagonist/-/protagonist-0.12.0.tgz
npm http 200 https://registry.npmjs.org/protagonist/-/protagonist-0.12.0.tgz

> protagonist@0.12.0 install /bright/forager/public/node_modules/protagonist
> node-gyp rebuild

make: Entering directory `/bright/forager/public/node_modules/protagonist/build'
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/HTTP.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/MarkdownBlock.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/MarkdownParser.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Parser.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/ParserCore.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Serialize.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeJSON.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeYAML.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/UriTemplateParser.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/snowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/csnowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprint.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CSourceAnnotation.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/posix/RegexMatch.o
  AR(target) Release/obj.target/snowcrash/snowcrash.a
  COPY Release/snowcrash.a
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/autolink.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/buffer.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/html/houdini_href_e.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/html/houdini_html_e.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/html/html.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/html/html_smartypants.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/markdown.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/stack.o
  CC(target) Release/obj.target/sundown/snowcrash/sundown/src/src_map.o
  AR(target) Release/obj.target/snowcrash/sundown.a
  COPY Release/sundown.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
In file included from ../src/annotation.cc:1:0:
../src/protagonist.h:12:47: error: expected class-name before ‘{’ token
../src/protagonist.h:27:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/protagonist.h:27:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/protagonist.h:34:54: error: expected class-name before ‘{’ token
../src/protagonist.h:46:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/protagonist.h:46:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/protagonist.h:53:44: error: expected class-name before ‘{’ token
../src/protagonist.h:67:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/protagonist.h:67:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/protagonist.h:74:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/protagonist.h:74:61: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h: In static member function ‘static void protagonist::SourceAnnotation::Init(v8::Handle<v8::Object>)’:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/annotation.cc:19:17: error: within this context
../src/annotation.cc:21:58: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../src/annotation.cc:21:58: note: candidate is:
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:3519:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:3519:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/annotation.cc:23:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/annotation.cc:25:61: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Local<v8::Function>)’
../src/annotation.cc:25:61: note: candidate is:
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:5757:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:5757:4: note:   candidate expects 2 arguments, 1 provided
../src/annotation.cc:26:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/annotation.cc: At global scope:
../src/annotation.cc:29:43: error: ‘Arguments’ does not name a type
../src/annotation.cc:29:54: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> protagonist::SourceAnnotation::New(const int&)’:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/annotation.cc:31:17: error: within this context
../src/annotation.cc:33:17: error: ‘class protagonist::SourceAnnotation’ has no member named ‘Wrap’
../src/annotation.cc:33:27: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
../src/annotation.cc:34:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/annotation.cc:34:29: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> protagonist::SourceAnnotation::NewInstance()’:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/annotation.cc:39:17: error: within this context
../src/annotation.cc:40:41: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Function>’
../src/annotation.cc:41:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/annotation.cc: In function ‘v8::Local<v8::Object> WrapSourceCharactersRange(const snowcrash::SourceCharactersRange&)’:
../src/annotation.cc:46:45: error: no matching function for call to ‘v8::Object::New()’
../src/annotation.cc:46:45: note: candidate is:
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:2457:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:2457:24: note:   candidate expects 1 argument, 0 provided
../src/annotation.cc:48:22: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/annotation.cc:48:76: error: no matching function for call to ‘v8::Number::New(const size_t&)’
../src/annotation.cc:48:76: note: candidate is:
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note:   candidate expects 2 arguments, 1 provided
../src/annotation.cc:49:22: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/annotation.cc:49:75: error: no matching function for call to ‘v8::Number::New(const size_t&)’
../src/annotation.cc:49:75: note: candidate is:
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note:   candidate expects 2 arguments, 1 provided
../src/annotation.cc: In static member function ‘static v8::Local<v8::Object> protagonist::SourceAnnotation::WrapSourceAnnotation(const snowcrash::SourceAnnotation&)’:
../src/annotation.cc:55:47: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Function>’
../src/annotation.cc:57:25: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/annotation.cc:57:79: error: no matching function for call to ‘v8::Number::New(const int&)’
../src/annotation.cc:57:79: note: candidate is:
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:2061:24: note:   candidate expects 2 arguments, 1 provided
../src/annotation.cc:58:25: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/annotation.cc:58:55: error: ‘New’ is not a member of ‘v8::String’
../src/annotation.cc:60:67: error: invalid conversion from ‘std::vector<snowcrash::SourceCharactersRange>::size_type {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
In file included from /home/vagrant/.node-gyp/0.11.13/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/vagrant/.node-gyp/0.11.13/deps/v8/include/v8.h:2486:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
../src/annotation.cc:69:25: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/annotation.cc: In static member function ‘static v8::Handle<v8::Value> protagonist::SourceAnnotation::NewInstance()’:
../src/annotation.cc:42:1: warning: control reaches end of non-void function [-Wreturn-type]
../src/annotation.cc: In static member function ‘static v8::Handle<v8::Value> protagonist::SourceAnnotation::New(const int&)’:
../src/annotation.cc:35:1: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
make: Leaving directory `/bright/forager/public/node_modules/protagonist/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/home/vagrant/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /bright/forager/public/node_modules/protagonist
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! protagonist@0.12.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@0.12.0 install script.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/home/vagrant/.nvm/v0.11.13/bin/node" "/home/vagrant/.nvm/v0.11.13/bin/npm" "install" "protagonist"
npm ERR! cwd /bright/forager/public
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /bright/forager/public/npm-debug.log
npm ERR! not ok code 0
```

**Comment by pksunkara** [comment]
If this hasn't been solved yet, you can try the proposed solutions in [apiaryio/snowcrash#63](https://github.com/apiaryio/snowcrash/issues/93#issuecomment-39346375) or danielgtaylor/aglio#16
