### ISSUE TITLE
Install failed on OS X

### ISSUE THREAD

**Issue by elmeister** [apiaryio/protagonist#249]
```
$ node -v
v8.15.1
$ npm -v
6.12.0
$ npm install protagonist@2.0.2

> protagonist@2.0.2 install /node_modules/protagonist
> node-gyp rebuild

  CXX(target) Release/obj.target/libdrafter/drafter/src/drafter.o
In file included from ../drafter/src/drafter.cc:10:
In file included from ../drafter/ext/snowcrash/src/snowcrash.h:12:
In file included from ../drafter/ext/snowcrash/src/BlueprintSourcemap.h:12:
In file included from ../drafter/ext/snowcrash/src/Blueprint.h:17:
../drafter/ext/snowcrash/src/MSON.h:351:19: error: constexpr constructor never produces a constant expression [-Winvalid-constexpr]
        constexpr Element() noexcept : content{} {}
                  ^
../drafter/ext/snowcrash/src/MSON.h:351:40: note: non-literal type 'Content' (aka 'variant<mpark::monostate, mson::PropertyMember, mson::ValueMember, mson::TypeDefinition, just<vector<mson::Element>, mson::one_of_tag>,
      just<vector<mson::Element>, mson::group_tag> >') cannot be used in a constant expression
        constexpr Element() noexcept : content{} {}
                                       ^
1 error generated.
make: *** [Release/obj.target/libdrafter/drafter/src/drafter.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/protagonist
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protagonist@2.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2019-11-25T06_19_20_794Z-debug.log
```

**Comment by kylef** [comment]
@elmeister can you share which version of macOS you are running and which version of the build tools (whether you've installed the command line build tools on macOS or which version of Xcode you have). Output of `clang --version` would be good to check.

**Comment by elmeister** [comment]
```
$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by kylef** [comment]
The version of LLVM is too old to support Drafter, the minimal compiler versions supported are listed at https://github.com/apiaryio/drafter/#installation.

It's a little complicated comparing those versions from `clang --version` since clang-800.0.42.1 is based on a much older LLVM upstream (LLVM 3.9 from 2016, the latest is LLVM 9) (https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_11.x_(since_Free_On-Device_Development)).

You can install a more modern command line tools / Xcode setup or LLVM/GCC from Homebrew (https://formulae.brew.sh/formula/llvm).

**Comment by elmeister** [comment]
I don't have Xcode installed at all actually. It's size is over 10 Gb, right? Just to use drafter.js... Never thought it's a system requirement.
