### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by demohi** [apiaryio/protagonist#34]
#### computer

![snip20141210_11](https://cloud.githubusercontent.com/assets/1209159/5372203/e5aac492-807f-11e4-9fb2-eea4b615fe61.png)

#### node&node-gyp version
node -v v0.11.14
node-gyp -v v1.0.2

#### error msg

```
../src/protagonist.h:13:36: error: expected class name
    class Blueprint : public node::ObjectWrap {
                                   ^
../src/protagonist.h:28:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:35:36: error: expected class name
    class Sourcemap : public node::ObjectWrap {
                                   ^
../src/protagonist.h:50:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:57:43: error: expected class name
    class SourceAnnotation : public node::ObjectWrap {
                                          ^
../src/protagonist.h:69:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:76:33: error: expected class name
    class Result : public node::ObjectWrap {
                                ^
../src/protagonist.h:92:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:99:46: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    extern v8::Handle<v8::Value> Parse(const v8::Arguments& args);
                                             ^~~~~~~~~~~~~
                                             v8::internal::Arguments
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/annotation.cc:19:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/annotation.cc:21:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:3435:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../src/annotation.cc:23:29: error: no member named 'NewSymbol' in 'v8::String'
    t->SetClassName(String::NewSymbol("SourceAnnotation"));
                    ~~~~~~~~^
../src/annotation.cc:25:41: error: 'New' is a private member of 'v8::PersistentBase<v8::Function>'
    constructor = Persistent<Function>::New(t->GetFunction());
                                        ^
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/annotation.cc:25:61: error: too few arguments to function call, expected 2, have 1
    constructor = Persistent<Function>::New(t->GetFunction());
                  ~~~~~~~~~~~~~~~~~~~~~~~~~                 ^
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:572:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8config.h:289:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../src/annotation.cc:26:26: error: no member named 'NewSymbol' in 'v8::String'
    exports->Set(String::NewSymbol("SourceAnnotation"), constructor);
                 ~~~~~~~~^
../src/annotation.cc:29:43: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> SourceAnnotation::New(const Arguments& args)
                                          ^~~~~~~~~
                                          v8::internal::Arguments
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/annotation.cc:31:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/annotation.cc:33:17: error: no member named 'Wrap' in 'protagonist::SourceAnnotation'
    annotation->Wrap(args.This());
    ~~~~~~~~~~  ^
../src/annotation.cc:33:26: error: member access into incomplete type 'const v8::internal::Arguments'
    annotation->Wrap(args.This());
                         ^
/Users/mdemo/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/mdemo/work/code/protagonist/node_modules/protagonist
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

```

**Comment by danielgtaylor** [comment]
It's worth nothing that the error from the first post also happens when trying to compile with [io.js 1.0.x](https://iojs.org/). It would be nice to have support for these newer versions/forks.

**Comment by zdne** [comment]
@jalberto can you please open a new issue with the full build output and your version node & gcc / llvm versions?  Thanks.

**Comment by zdne** [comment]
@danielgtaylor The issue for support of v0.11 can be tracked here https://github.com/apiaryio/protagonist/issues/16
