### ISSUE TITLE
`npm install protagonist` files with Node.js 0.12.0 on Arch Linux

### ISSUE THREAD

**Issue by lukebond** [apiaryio/protagonist#43]
I have a project using Aglio that I cannot `npm install` with my current setup due to protagonist failing.

```
$ npm install
...
> protagonist@0.17.1 install /home/luke/Development/paz/paz-orchestrator/node_modules/aglio/node_modules/protagonist
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/luke/Development/paz/paz-orchestrator/node_modules/aglio/node_modules/protagonist/build'
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprint.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprintSourcemap.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CSourceAnnotation.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/HTTP.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Section.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Serialize.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeJSON.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeYAML.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Signature.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/snowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/csnowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/UriTemplateParser.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/posix/RegexMatch.o
  AR(target) Release/obj.target/snowcrash/snowcrash.a
  COPY Release/snowcrash.a
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/ByteBuffer.o
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownNode.o
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownParser.o
  AR(target) Release/obj.target/snowcrash/markdownparser.a
  COPY Release/markdownparser.a
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/autolink.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/buffer.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/markdown.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/src_map.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/stack.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_href_e.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_html_e.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html_smartypants.o
  AR(target) Release/obj.target/snowcrash/sundown.a
  COPY Release/sundown.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
In file included from ../src/annotation.cc:1:0:
../src/protagonist.h:13:47: error: expected class-name before ‘{’ token
     class Blueprint : public node::ObjectWrap {
                                               ^
../src/protagonist.h:28:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/protagonist.h:35:47: error: expected class-name before ‘{’ token
     class Sourcemap : public node::ObjectWrap {
                                               ^
../src/protagonist.h:50:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/protagonist.h:57:54: error: expected class-name before ‘{’ token
     class SourceAnnotation : public node::ObjectWrap {
                                                      ^
../src/protagonist.h:69:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/protagonist.h:76:44: error: expected class-name before ‘{’ token
     class Result : public node::ObjectWrap {
                                            ^
../src/protagonist.h:92:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/protagonist.h:99:50: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     extern v8::Handle<v8::Value> Parse(const v8::Arguments& args);
                                                  ^
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static void protagonist::SourceAnnotation::Init(v8::Handle<v8::Object>)’:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/annotation.cc:19:17: error: within this context
     HandleScope scope;
                 ^
../src/annotation.cc:21:58: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                          ^
../src/annotation.cc:21:58: note: candidate is:
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/annotation.cc:23:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
     t->SetClassName(String::NewSymbol("SourceAnnotation"));
                     ^
../src/annotation.cc:25:61: error: no matching function for call to ‘v8::Persistent<v8::Function>::New(v8::Local<v8::Function>)’
     constructor = Persistent<Function>::New(t->GetFunction());
                                                             ^
../src/annotation.cc:25:61: note: candidate is:
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note:   candidate expects 2 arguments, 1 provided
../src/annotation.cc:26:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     exports->Set(String::NewSymbol("SourceAnnotation"), constructor);
                  ^
../src/annotation.cc: At global scope:
../src/annotation.cc:29:43: error: ‘Arguments’ does not name a type
 Handle<Value> SourceAnnotation::New(const Arguments& args)
                                           ^
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> protagonist::SourceAnnotation::New(const int&)’:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/annotation.cc:31:17: error: within this context
     HandleScope scope;
                 ^
../src/annotation.cc:33:17: error: ‘class protagonist::SourceAnnotation’ has no member named ‘Wrap’
     annotation->Wrap(args.This());
                 ^
../src/annotation.cc:33:27: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
     annotation->Wrap(args.This());
                           ^
../src/annotation.cc:34:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(args.This());
                  ^
../src/annotation.cc:34:29: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
     return scope.Close(args.This());
                             ^
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> protagonist::SourceAnnotation::NewInstance()’:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/annotation.cc:39:17: error: within this context
     HandleScope scope;
                 ^
../src/annotation.cc:40:41: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Function>’
     Local<Object> instance = constructor->NewInstance();
                                         ^
../src/annotation.cc:41:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(instance);
                  ^
../src/annotation.cc: In function ‘v8::Local<v8::Object> WrapSourceCharactersRange(const CharactersRange&)’:
../src/annotation.cc:46:45: error: no matching function for call to ‘v8::Object::New()’
     Local<Object> rangeObject = Object::New();
                                             ^
../src/annotation.cc:46:45: note: candidate is:
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/annotation.cc:48:22: error: ‘NewSymbol’ is not a member of ‘v8::String’
     rangeObject->Set(String::NewSymbol("index"), Number::New(range.location));
                      ^
../src/annotation.cc:48:76: error: no matching function for call to ‘v8::Number::New(const size_t&)’
     rangeObject->Set(String::NewSymbol("index"), Number::New(range.location));
                                                                            ^
../src/annotation.cc:48:76: note: candidate is:
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/annotation.cc:49:22: error: ‘NewSymbol’ is not a member of ‘v8::String’
     rangeObject->Set(String::NewSymbol("length"), Number::New(range.length));
                      ^
../src/annotation.cc:49:75: error: no matching function for call to ‘v8::Number::New(const size_t&)’
     rangeObject->Set(String::NewSymbol("length"), Number::New(range.length));
                                                                           ^
../src/annotation.cc:49:75: note: candidate is:
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/annotation.cc: In static member function ‘static v8::Local<v8::Object> protagonist::SourceAnnotation::WrapSourceAnnotation(const snowcrash::SourceAnnotation&)’:
../src/annotation.cc:55:47: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Function>’
     Local<Object> annotationWrap = constructor->NewInstance();
                                               ^
../src/annotation.cc:57:25: error: ‘NewSymbol’ is not a member of ‘v8::String’
     annotationWrap->Set(String::NewSymbol("code"), Number::New(annotation.code));
                         ^
../src/annotation.cc:57:79: error: no matching function for call to ‘v8::Number::New(const int&)’
     annotationWrap->Set(String::NewSymbol("code"), Number::New(annotation.code));
                                                                               ^
../src/annotation.cc:57:79: note: candidate is:
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/annotation.cc:58:25: error: ‘NewSymbol’ is not a member of ‘v8::String’
     annotationWrap->Set(String::NewSymbol("message"), String::New(annotation.message.c_str()));
                         ^
../src/annotation.cc:58:55: error: ‘New’ is not a member of ‘v8::String’
     annotationWrap->Set(String::NewSymbol("message"), String::New(annotation.message.c_str()));
                                                       ^
../src/annotation.cc:60:66: error: invalid conversion from ‘std::vector<mdp::Range, std::allocator<mdp::Range> >::size_type {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
     Local<Object> location = Array::New(annotation.location.size());
                                                                  ^
In file included from /home/luke/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/protagonist.h:1,
                 from ../src/annotation.cc:1:
/home/luke/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:23: note: initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../src/annotation.cc:69:25: error: ‘NewSymbol’ is not a member of ‘v8::String’
     annotationWrap->Set(String::NewSymbol("location"), location);    
                         ^
../src/annotation.cc: In static member function ‘static v8::Handle<v8::Value> protagonist::SourceAnnotation::New(const int&)’:
../src/annotation.cc:35:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/annotation.cc: In static member function ‘static v8::Handle<v8::Value> protagonist::SourceAnnotation::NewInstance()’:
../src/annotation.cc:42:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
protagonist.target.mk:123: recipe for target 'Release/obj.target/protagonist/src/annotation.o' failed
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
make: Leaving directory '/home/luke/Development/paz/paz-orchestrator/node_modules/aglio/node_modules/protagonist/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.18.6-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/luke/Development/paz/paz-orchestrator/node_modules/aglio/node_modules/protagonist
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.18.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! protagonist@0.17.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@0.17.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/luke/Development/paz/paz-orchestrator/npm-debug.log
```

As the output shows, I'm using Node.js 0.12.0 and npm 2.5.1. gcc version is  4.9.2.

If I downgrade to Node.js 0.10.36 it works fine.

**Comment by adamgross42** [comment]
I'm seeing this as well, starting yesterday :disappointed:

**Comment by zdne** [comment]
Node > v0.11 isn't supported in the stable branch – see https://github.com/apiaryio/protagonist/issues/16 for details –

**Comment by zdne** [comment]
Long story v0.11 introduced some API breaking changes, we have addressed them in the experimental version, stable release pending. Closing as duplicate to https://github.com/apiaryio/protagonist/issues/16
