### ISSUE TITLE
node-gyp compilation failed

### ISSUE THREAD

**Issue by njl07** [apiaryio/protagonist#50]
Hello,

I want to use your plugin and when I try to install it, some errors occurred:

```
In file included from ../src/annotation.cc:1:
../src/protagonist.h:13:36: error: expected class name
    class Blueprint : public node::ObjectWrap {
                                   ^
../src/protagonist.h:28:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:35:36: error: expected class name
    class Sourcemap : public node::ObjectWrap {
                                   ^
../src/protagonist.h:50:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:57:43: error: expected class name
    class SourceAnnotation : public node::ObjectWrap {
                                          ^
../src/protagonist.h:69:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:76:33: error: expected class name
    class Result : public node::ObjectWrap {
                                ^
../src/protagonist.h:92:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:99:46: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    extern v8::Handle<v8::Value> Parse(const v8::Arguments& args);
                                             ^~~~~~~~~~~~~
                                             v8::internal::Arguments
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/annotation.cc:19:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/annotation.cc:21:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../src/annotation.cc:23:29: error: no member named 'NewSymbol' in 'v8::String'
    t->SetClassName(String::NewSymbol("SourceAnnotation"));
                    ~~~~~~~~^
../src/annotation.cc:25:41: error: 'New' is a private member of 'v8::PersistentBase<v8::Function>'
    constructor = Persistent<Function>::New(t->GetFunction());
                                        ^
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/annotation.cc:25:61: error: too few arguments to function call, expected 2, have 1
    constructor = Persistent<Function>::New(t->GetFunction());
                  ~~~~~~~~~~~~~~~~~~~~~~~~~                 ^
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:572:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8config.h:289:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../src/annotation.cc:26:26: error: no member named 'NewSymbol' in 'v8::String'
    exports->Set(String::NewSymbol("SourceAnnotation"), constructor);
                 ~~~~~~~~^
../src/annotation.cc:29:43: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> SourceAnnotation::New(const Arguments& args)
                                          ^~~~~~~~~
                                          v8::internal::Arguments
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/annotation.cc:31:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/annotation.cc:33:17: error: no member named 'Wrap' in 'protagonist::SourceAnnotation'
    annotation->Wrap(args.This());
    ~~~~~~~~~~  ^
../src/annotation.cc:33:26: error: member access into incomplete type 'const v8::internal::Arguments'
    annotation->Wrap(args.This());
                         ^
/Users/njl/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/njl/Programmation/InTech/WEGA-API/wega-doc/node_modules/aglio/node_modules/protagonist
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "aglio"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE
```

Can you help me on this issue?

Thanks.

**Comment by pksunkara** [comment]
@njl07 You node.js version is 0.12.x. `protagonist` does not support node.js 0.11 or 0.12. We have a beta release at `protagonist-experimental` which does support them though.

Refer to #16.

**Comment by zdne** [comment]
@njl07 note we will be releasing stable version of protagonist that supports io.js and node >= v0.11 in the course of few weeks (until then please use protagonist-experimental as @pksunkara suggests)
