### ISSUE TITLE
Error: connect ECONNREFUSED on CircleCI

### ISSUE THREAD

**Issue by philsturgeon** [apiaryio/protagonist#71]
I'm trying to install dredd via `npm install -g dredd`. It's been working for months, but I tried updating versions of dredd, then rolled back to the same version and now this error is spitting out. Tried rebuilding without the cache and no joy there. 

```
> protagonist@0.19.6 install /home/ubuntu/nvm/v0.10.33/lib/node_modules/dredd/node_modules/drafter/node_modules/protagonist
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ECONNREFUSED
gyp ERR! stack     at errnoException (net.js:904:11)
gyp ERR! stack     at Object.afterConnect [as oncomplete] (net.js:895:19)
gyp ERR! System Linux 3.14.28-031428-generic
gyp ERR! command "node" "/home/ubuntu/nvm/v0.10.33/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/nvm/v0.10.33/lib/node_modules/dredd/node_modules/drafter/node_modules/protagonist
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.14.28-031428-generic
npm ERR! argv "node" "/home/ubuntu/nvm/v0.10.33/bin/npm" "install" "-g" "dredd"
npm ERR! node v0.10.33
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE

npm ERR! protagonist@0.19.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@0.19.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/central-api/npm-debug.log

npm install -g dredd returned exit code 1
```

The contents of that log are [here](https://gist.githubusercontent.com/philsturgeon/f1631f0de1a3440b0b15/raw/gistfile1.txt).

**Comment by zdne** [comment]
Hey @philsturgeon I wonder where the CircleCI is coming from. 

I've just tried to install latest Dredd and seems to work OK:

```shell
yt:T z$ npm i dredd
npm WARN engine uri-template@1.0.0: wanted: {"node":"~0.10.4"} (current: {"node":"0.12.3","npm":"2.9.1"})
\
> protagonist@0.19.6 install /Users/z/Desktop/T/node_modules/dredd/node_modules/drafter/node_modules/protagonist
> node-gyp rebuild

  CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.o
  CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/MarkdownNode.o
  CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/MarkdownParser.o
  LIBTOOL-STATIC Release/markdownparser.a
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/HTTP.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSON.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSONOneOfParser.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSONSourcemap.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSONTypeSectionParser.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/MSONValueMemberParser.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/Blueprint.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/BlueprintSourcemap.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/Section.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/Signature.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/snowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/UriTemplateParser.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/HeadersParser.o
  CXX(target) Release/obj.target/libsnowcrash/drafter/ext/snowcrash/src/posix/RegexMatch.o
  LIBTOOL-STATIC Release/snowcrash.a
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/autolink.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/buffer.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/markdown.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/src_map.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/stack.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_href_e.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_html_e.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/html/html.o
  CC(target) Release/obj.target/libsundown/drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/html/html_smartypants.o
  LIBTOOL-STATIC Release/sundown.a
  CXX(target) Release/obj.target/libdrafter/drafter/src/drafter.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/cdrafter.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/Serialize.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/SerializeAST.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/SerializeSourcemap.o
  CXX(target) Release/obj.target/libdrafter/drafter/src/SerializeResult.o
  LIBTOOL-STATIC Release/drafter.a
  CXX(target) Release/obj.target/libsos/drafter/ext/sos/src/sos.o
  LIBTOOL-STATIC Release/sos.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
  CXX(target) Release/obj.target/protagonist/src/parse.o
  CXX(target) Release/obj.target/protagonist/src/protagonist.o
  CXX(target) Release/obj.target/protagonist/src/result.o
  CXX(target) Release/obj.target/protagonist/src/v8_wrapper.o
  SOLINK_MODULE(target) Release/protagonist.node
  SOLINK_MODULE(target) Release/protagonist.node: Finished
dredd@0.5.4 node_modules/dredd
├── setimmediate@1.0.2
├── file@0.2.2
├── htmlencode@0.0.4
├── clone@1.0.2
├── node-uuid@1.4.3
├── advisable@0.2.0
├── proxyquire@1.4.0
├── uri-template@1.0.0 (pct-encode@1.0.1)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── coffee-script@1.9.3
├── async@1.1.0
├── chai@2.3.0 (assertion-error@1.0.0, deep-eql@0.1.3)
├── pitboss-ng@0.3.2 (pidusage@0.1.1, csv@0.4.2)
├── html@0.0.10 (glob@3.2.11, concat-stream@1.4.8)
├── js-yaml@3.3.1 (esprima@2.2.0, argparse@1.0.2)
├── markdown-it@4.2.1 (linkify-it@1.1.0, mdurl@1.0.0, uc.micro@1.0.0, entities@1.1.1, argparse@1.0.2)
├── inquirer@0.8.5 (figures@1.3.5, ansi-regex@1.1.1, cli-width@1.0.1, through@2.3.7, readline2@0.1.1, chalk@1.0.0, lodash@3.9.3, rx@2.5.3)
├── winston@1.0.0 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, pkginfo@0.3.0, async@0.9.2, colors@1.0.3)
├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── request@2.57.0 (caseless@0.10.0, aws-sign2@0.5.0, stringstream@0.0.4, forever-agent@0.6.1, tunnel-agent@0.4.0, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, qs@3.1.0, tough-cookie@1.2.0, combined-stream@1.0.3, mime-types@2.0.13, form-data@0.2.0, bl@0.9.4, http-signature@0.11.0, hawk@2.3.1, har-validator@1.7.1)
├── gavel@0.5.2 (caseless@0.10.0, media-typer@0.3.0, deep-equal@1.0.0, tv4@1.1.9, http-string-parser@0.0.5, is-type@0.0.1, googlediff@0.1.0, commander@2.8.1, amanda@0.5.1, json-pointer@0.3.0, curl-trace-parser@0.0.8, jsonlint@1.6.2)
└── drafter@0.2.7 (deep-equal@1.0.0, async@0.9.2, yargs@1.3.3, deepcopy@0.4.0, boutique@0.1.7, protagonist@0.19.6)
yt:T z$ 
```

Note this might be a question for @netmilk as this doesn't seem to be a problem with Protagonsit itself (both 0.19 and 0.20 install just fine for me).

Does the problem persist?

**Comment by philsturgeon** [comment]
Retried the failing build this morning and its stopped.

**Comment by zdne** [comment]
I do not want to call names but I really dislike this `npm` thing...

**Comment by zdne** [comment]
Either way, let us know if something. Closing.

**Comment by philsturgeon** [comment]
0./
