### ISSUE TITLE
Problem install 0.20 at mac (node 0.10.37, npm 2.10.1)

### ISSUE THREAD

**Issue by abtris** [apiaryio/protagonist#72]
```
$ npm i protagonist
\
> protagonist@0.20.0 install /private/tmp/node_modules/protagonist
> node-gyp rebuild

  CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.o
In file included from ../drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.cc:9:
In file included from ../drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.h:14:
In file included from /usr/include/c++/4.2.1/sstream:44:
In file included from /usr/include/c++/4.2.1/istream:845:
In file included from /usr/include/c++/4.2.1/bits/istream.tcc:46:
/usr/bin/locale:1:1: error: source file is not valid UTF-8
<CF><FA><ED><FE><U+0007>
^
/usr/bin/locale:1:2: error: source file is not valid UTF-8
<CF><FA><ED><FE><U+0007>
    ^
/usr/bin/locale:1:3: error: source file is not valid UTF-8
<CF><FA><ED><FE><U+0007>
        ^
/usr/bin/locale:1:4: error: source file is not valid UTF-8
<CF><FA><ED><FE><U+0007>
            ^
/usr/bin/locale:1:5: error: expected unqualified-id
<CF><FA><ED><FE><U+0007>
                ^
/usr/bin/locale:1:12: error: source file is not valid UTF-8
<CF><FA><ED><FE><U+0007><U+0000><U+0000><U+0001><U+0003><U+0000><U+0000><80><U+0002>
                                                                        ^
/usr/bin/locale:1:25: error: source file is not valid UTF-8
  ...<85><80>!
     ^
/usr/bin/locale:1:26: error: source file is not valid UTF-8
  ...<80>!
     ^
/usr/bin/locale:1:138: error: source file is not valid UTF-8
  ...<C0>
     ^
/usr/bin/locale:1:154: error: source file is not valid UTF-8
  ...<C0>
     ^
/usr/bin/locale:1:244: error: source file is not valid UTF-8
  ...<80>
     ^
/usr/bin/locale:1:289: error: source file is not valid UTF-8
  ...<88><8F>
     ^
/usr/bin/locale:1:290: error: source file is not valid UTF-8
  ...<8F>
     ^
/usr/bin/locale:1:305: error: source file is not valid UTF-8
  ...<88><8F>
     ^
/usr/bin/locale:1:306: error: source file is not valid UTF-8
  ...<8F>
     ^
/usr/bin/locale:1:324: error: source file is not valid UTF-8
  ...<80>
     ^
/usr/bin/locale:1:369: error: non-ASCII characters are not allowed outside of literals and identifiers
  ...Ԑ
     ^
/usr/bin/locale:1:385: error: non-ASCII characters are not allowed outside of literals and identifiers
  ...Ԑ
     ^
/usr/bin/locale:1:404: error: source file is not valid UTF-8
  ...<80>
     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/abtris/.nvm/v0.10.37/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/abtris/.nvm/v0.10.37/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/node_modules/protagonist
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/abtris/.nvm/v0.10.37/bin/npm" "i" "protagonist"
npm ERR! node v0.10.37
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! protagonist@0.20.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protagonist@0.20.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/abtris/.nvm/v0.10.37/bin/npm',
1 verbose cli   'i',
1 verbose cli   'protagonist' ]
2 info using npm@2.10.1
3 info using node@v0.10.37
4 verbose install initial load of /private/tmp/package.json
5 verbose installManyTop reading scoped package data from /private/tmp/node_modules/node-gyp/package.json
6 verbose readDependencies loading dependencies from /private/tmp/package.json
7 silly cache add args [ 'protagonist', null ]
8 verbose cache add spec protagonist
9 silly cache add parsed spec { raw: 'protagonist',
9 silly cache add   scope: null,
9 silly cache add   name: 'protagonist',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed protagonist@*
11 verbose addNamed "*" is a valid semver range for protagonist
12 silly addNameRange { name: 'protagonist', range: '*', hasData: false }
13 silly mapToRegistry name protagonist
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/protagonist
17 verbose addNameRange registry:https://registry.npmjs.org/protagonist not in flight; fetching
18 verbose request uri https://registry.npmjs.org/protagonist
19 verbose request no auth needed
20 info attempt registry request try #1 at 08:59:08
21 verbose request using bearer token for auth
22 verbose request id 257b78d39981bb37
23 verbose etag "1AT7SLADF878Z1SQ4J5F4CHWG"
24 http request GET https://registry.npmjs.org/protagonist
25 http 304 https://registry.npmjs.org/protagonist
26 silly get cb [ 304,
26 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
26 silly get     etag: '"1AT7SLADF878Z1SQ4J5F4CHWG"',
26 silly get     'cache-control': 'max-age=60',
26 silly get     'accept-ranges': 'bytes',
26 silly get     date: 'Tue, 09 Jun 2015 06:59:09 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-lcy1131-LCY',
...skipping...
1203 verbose linkBins protagonist@0.20.0
1204 verbose linkMans protagonist@0.20.0
1205 verbose rebuildBundles protagonist@0.20.0
1206 verbose rebuildBundles [ 'nan' ]
1207 info install protagonist@0.20.0
1208 verbose unsafe-perm in lifecycle true
1209 info protagonist@0.20.0 Failed to exec install script
1210 verbose unlock done using /Users/abtris/.npm/_locks/protagonist-29a37ccd43d61712.lock for /private/tmp/node_modules/protagonist
1211 verbose stack Error: protagonist@0.20.0 install: `node-gyp rebuild`
1211 verbose stack Exit status 1
1211 verbose stack     at EventEmitter.<anonymous> (/Users/abtris/.nvm/v0.10.37/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
1211 verbose stack     at EventEmitter.emit (events.js:98:17)
1211 verbose stack     at ChildProcess.<anonymous> (/Users/abtris/.nvm/v0.10.37/lib/node_modules/npm/lib/utils/spawn.js:24:14)
1211 verbose stack     at ChildProcess.emit (events.js:98:17)
1211 verbose stack     at maybeClose (child_process.js:766:16)
1211 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
1212 verbose pkgid protagonist@0.20.0
1213 verbose cwd /private/tmp
1214 error Darwin 14.3.0
1215 error argv "node" "/Users/abtris/.nvm/v0.10.37/bin/npm" "i" "protagonist"
1216 error node v0.10.37
1217 error npm  v2.10.1
1218 error code ELIFECYCLE
1219 error protagonist@0.20.0 install: `node-gyp rebuild`
1219 error Exit status 1
1220 error Failed at the protagonist@0.20.0 install script 'node-gyp rebuild'.
1220 error This is most likely a problem with the protagonist package,
1220 error not with npm itself.
1220 error Tell the author that this fails on your system:
1220 error     node-gyp rebuild
1220 error You can get their info via:
1220 error     npm owner ls protagonist
1220 error There is likely additional logging output above.
1221 verbose exit [ 1, true ]
1222 verbose unbuild node_modules/protagonist
1223 info preuninstall protagonist@0.20.0
1224 info uninstall protagonist@0.20.0
1225 verbose unbuild rmStuff protagonist@0.20.0 from /private/tmp/node_modules
1226 info postuninstall protagonist@0.20.0
1227 silly gentlyRm /private/tmp/node_modules/protagonist is being purged from base /private/tmp
1228 verbose gentlyRm don't care about contents; nuking /private/tmp/node_modules/protagonist
1229 silly vacuum-fs purging /private/tmp/node_modules/protagonist
1230 silly vacuum-fs quitting because other entries in /private/tmp/node_modules
```

**Comment by pksunkara** [comment]
:open_mouth: I don't even know what happened. Is this a protagonist issue for sure?

**Comment by abtris** [comment]
Can be problem in gcc 4.2.1 ?

**Comment by abtris** [comment]
@pksunkara Can someone add BOM into sources? http://stackoverflow.com/questions/26788871/error-source-file-is-not-valid-utf-8

**Comment by pksunkara** [comment]
@abtris I think this is a problem with gcc.

**Comment by abtris** [comment]
Looks as clang 6.0.1 related problem. But I don't know any good solution.

**Comment by abtris** [comment]
I try this and compile with gcc at mac works: 
```
export CC=/usr/local/Cellar/gcc48/4.8.4/bin/gcc-4.8
export CXX=/usr/local/Cellar/gcc48/4.8.4/bin/g++-4.8
```
and patch file `drafter/ext/snowcrash/src/StringUtility.h` comment line 17 `// #include <locale>`

**Comment by pksunkara** [comment]
Does commenting out header `locale` work with the original clang version?

**Comment by zdne** [comment]
@klokane can you please look into this?

**Comment by klokane** [comment]
@pksunkara @zdne I already look at it w/ @abtris what he wrote is result what we found.
Trouble is I'm not on mac to check it.

**Comment by klokane** [comment]
I've used clear installation of mac with:

$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

Compiled w/o problem

$ npm install protagonist

Is OK too

**Comment by pksunkara** [comment]
Okay, so it looks like it's an error with @abtris computer.

**Comment by klokane** [comment]
Yee, probably some corrupted system include files?

**Comment by pksunkara** [comment]
@abtris Is this fixed?

**Comment by abtris** [comment]
Yes, you can close. We don't find solution.
