### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by sheshmantha** [apiaryio/protagonist#76]
Hi,
Loaded protagonist and tried `npm test`.   First it complained that mocha "is not recognized".  Did an `npm install -g mocha`.  Then re-ran test and now am getting the following error.
```
> protagonist@0.20.1 test C:\protagonist\node_modules\protagonist
> mocha --compilers coffee:coffee-script -R spec ./test/*-test.coffee

C:\protagonist\node_modules\protagonist\test\ast-test.coffee:1
function (exports, require, module, __filename, __dirname) { fs = require 'fs'
                                                                         ^^^^
SyntaxError: Unexpected string
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:443:25)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at C:\Users\smantha\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:192:27
  at Array.forEach (native)
  at Mocha.loadFiles (C:\Users\smantha\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:189:14)
  at Mocha.run (C:\Users\smantha\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:422:31)
  at Object.<anonymous> (C:\Users\smantha\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:398:16)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
npm ERR! Test failed.  See above for more details.
```
How to fix this?  What am I missing?  How to check for what I could be missing ?

Thanks,
S-

**Comment by pksunkara** [comment]
You need to run `npm install` to install all the dependencies.

**Comment by sheshmantha** [comment]
oh! cool -- thank you.  that worked.
